// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZFTiySNKGfZNVkCQfjocL_s61MwVaoNw',
    appId: '1:142353796421:web:0eb4ccc0da2d9a36ac422c',
    messagingSenderId: '142353796421',
    projectId: 'mynotes-5c1db',
    authDomain: 'mynotes-5c1db.firebaseapp.com',
    storageBucket: 'mynotes-5c1db.appspot.com',
    measurementId: 'G-M197DD3H7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCLTU55DBWXjbLLut0B_bptUuOKYvPEA4',
    appId: '1:142353796421:android:c064e765b204236aac422c',
    messagingSenderId: '142353796421',
    projectId: 'mynotes-5c1db',
    storageBucket: 'mynotes-5c1db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMBR--Ty5X4QePCr0GJvWf8zds4LFtakQ',
    appId: '1:142353796421:ios:e892daa16f307162ac422c',
    messagingSenderId: '142353796421',
    projectId: 'mynotes-5c1db',
    storageBucket: 'mynotes-5c1db.appspot.com',
    iosClientId: '142353796421-ifjrl6tm5sj02vaoe33ajakhush5n12v.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningdart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMBR--Ty5X4QePCr0GJvWf8zds4LFtakQ',
    appId: '1:142353796421:ios:e892daa16f307162ac422c',
    messagingSenderId: '142353796421',
    projectId: 'mynotes-5c1db',
    storageBucket: 'mynotes-5c1db.appspot.com',
    iosClientId: '142353796421-ifjrl6tm5sj02vaoe33ajakhush5n12v.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningdart',
  );
}
